version: '3.8'
services:
  # MongoDB dev container
  mongodb:
    image: mongo:latest 
    container_name: mongodb-dev-c
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes: 
      - mongodb-dev:/data/db 
  
  # Mongo Express container 
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-c
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb-dev-c 
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
 
  # Redis cache container
  redis:
    image: redis:latest
    container_name: redis-cache-c 
    restart: always
    ports:
      - 6379:6379

volumes:
  mongodb-dev:

